# Generated by Django 5.1.1 on 2024-10-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('Nombre', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=800)),
            ],
        ),
    ]
