# Generated by Django 5.1.1 on 2024-10-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('Nombre', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=800)),
            ],
        ),
        migrations.DeleteModel(
            name='Proyectos',
        ),
    ]
