# Generated by Django 5.1.1 on 2024-10-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adminis',
            fields=[
                ('Title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Descrip', models.CharField(max_length=200)),
                ('Checked', models.BooleanField()),
            ],
        ),
    ]
