# Generated by Django 5.1.1 on 2024-10-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminis',
            name='Checked',
        ),
    ]
