# Generated by Django 5.1.1 on 2024-10-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto1', '0002_remove_adminis_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminis',
            name='Checked',
            field=models.BooleanField(default=False),
        ),
    ]
