# Generated by Django 5.1.1 on 2024-10-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto1', '0003_adminis_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminis',
            name='Checked',
        ),
    ]
